### PR TITLE
Rename Consent object to GovSingleConsent

### PR DESCRIPTION
**Pull request by andyhd**
* Avoid collisions with 3rd party Javascripts
* Also rename URL parameter and cookie

### CODE REVIEW

**Comment by andyhd** [comment]
End-to-end tests are failing because the dummy services are not using the version of the client JS from this PR. The test env setup needs to build dummy services instead of downloading them from Google Container Repository.

**Review by guifry — DISMISSED** [review]
LGTM

**Comment by guifry** [comment]
Closing this PR in favour of [this one](https://github.com/alphagov/consent-api/pull/159), since the diverging commits had introduced too many conflicts

**Comment by guifry** [comment]
Closing this PR in favour of [this one](https://github.com/alphagov/consent-api/pull/159), since the diverging commits had introduced too many conflicts

**Pull request closed without merging**
